### ISSUE TITLE
Route URLs are not consistent with menu

### ISSUE THREAD

**Issue by danrocha** [aecworks/aec.works-web#41]
When you click on the menu item "feed," it currently goes to `/posts`

We could change it to `/feed`, as "companies" goes to `/companies` and "people" goes to `/people`

**Comment by Shweta200126** [comment]
@danrocha link  to the page would be nice

**Comment by Kukulim** [comment]
Hi, i add pull request to fix it.

**Comment by gtalarico** [comment]
@Shweta200126 good call, fixed on #47
