### ISSUE TITLE
Company cards: make logo and cover clickable

### ISSUE THREAD

**Issue by danrocha** [aecworks/aec.works-web#50]
Currently, the only link to the company page is the `h2` with the company name. 

We could include a link on both the cover image and the logo as well.

![image](https://user-images.githubusercontent.com/5139870/95561012-6089c080-0a1a-11eb-9bd9-4a356f51f953.png)

The logo also currently has a `cursor: pointer;` style to it, but it is not clickable.

**Comment by gtalarico** [comment]
Agree 👍
