### ISSUE TITLE
Login modal uses rounded corners

### ISSUE THREAD

**Issue by danrocha** [aecworks/aec.works-web#9]
While our aethetics is full-on sharp corners, the login modal uses round corners. 

<img width="651" alt="Screenshot 2020-09-24 at 14 20 50" src="https://user-images.githubusercontent.com/5139870/94145274-93f11a80-fe72-11ea-9085-00e442eb5cc4.png">

**Comment by gtalarico** [comment]
good eye 👁️  for for it!
